### ISSUE TITLE
adjust check chunks before delete

### ISSUE THREAD

**Issue by perrozzi** [perrozzi/cmg-cmssw#10]
currently file is checked to be not empty, need to implement opening of the file and random histo or something similar. corrupted empty files of few bytes can exist an are not currently catched

**Comment by perrozzi** [comment]
this should have been fixed here
https://github.com/perrozzi/cmg-cmssw/commit/785e2ab1b5d576504350daf0f92baf55f58f3af7

**Comment by 12345ieee** [comment]
Definitely fixed, can be closed.
