### ISSUE TITLE
Check the sqrt(3.7) normalization

### ISSUE THREAD

**Issue by 12345ieee** [perrozzi/cmg-cmssw#12]
As title said, something is amiss in the normalization for data and MC, resulting in a sqrt(3.7) out of nowhere.

Needs to be checked.

**Comment by perrozzi** [comment]
this should have been fixed here
https://github.com/perrozzi/cmg-cmssw/commit/ee497f94dd190a9f39f5f903939e0571ed8cb748#diff-83a0900eba90a23981c5e36adafc339c
https://github.com/perrozzi/cmg-cmssw/commit/09f37bf94467f374798f0fa0f1712d01af080932#diff-83a0900eba90a23981c5e36adafc339c

**Comment by 12345ieee** [comment]
This fixes the factor of 4, have you had any luck with the remaining 30% ?

**Comment by perrozzi** [comment]
after the fix:
data integral 157081
mcdatalikepow integral 153996
ratio data/mc = 1.020
I would say it's ok :-)

**Comment by 12345ieee** [comment]
Great, I close the issue.
